python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_matou_os_peixes.txt 3 7
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_matou_os_peixes.txt 3 7
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_matou_os_peixes.txt 3 7
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_matou_os_peixes.txt 3 7
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_matou_os_peixes.txt 3 7
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Maca_no_Escuro.txt 3 6
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Maca_no_Escuro.txt 3 6
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Maca_no_Escuro.txt 3 6
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Maca_no_Escuro.txt 3 6
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Maca_no_Escuro.txt 3 6
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_a_bela_e_a_fera.txt 3 5
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_a_bela_e_a_fera.txt 3 5
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_a_bela_e_a_fera.txt 3 5
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_a_bela_e_a_fera.txt 3 5
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_a_bela_e_a_fera.txt 3 5
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Descoberta_do_Mundo.txt 3 8
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Descoberta_do_Mundo.txt 3 8
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Descoberta_do_Mundo.txt 3 8
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Descoberta_do_Mundo.txt 3 8
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Descoberta_do_Mundo.txt 3 8
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_Dona_flor_seus_dois_maridos.txt 4 9
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_Dona_flor_seus_dois_maridos.txt 4 9
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_Dona_flor_seus_dois_maridos.txt 4 9
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_Dona_flor_seus_dois_maridos.txt 4 9
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_Dona_flor_seus_dois_maridos.txt 4 9
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_pastores_noite.txt 4 10
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_pastores_noite.txt 4 10
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_pastores_noite.txt 4 10
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_pastores_noite.txt 4 10
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_pastores_noite.txt 4 10
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_clarissa.txt 5 12
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_clarissa.txt 5 12
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_clarissa.txt 5 12
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_clarissa.txt 5 12
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_clarissa.txt 5 12
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_Caminhos_Cruzados.txt 5 13
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_Caminhos_Cruzados.txt 5 13
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_Caminhos_Cruzados.txt 5 13
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_Caminhos_Cruzados.txt 5 13
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_Caminhos_Cruzados.txt 5 13
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_olhai_os_lirios_dos_campos.txt 5 14
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_olhai_os_lirios_dos_campos.txt 5 14
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_olhai_os_lirios_dos_campos.txt 5 14
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_olhai_os_lirios_dos_campos.txt 5 14
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_olhai_os_lirios_dos_campos.txt 5 14
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_o_lustre.txt 3 15
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_o_lustre.txt 3 15
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_o_lustre.txt 3 15
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_o_lustre.txt 3 15
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_o_lustre.txt 3 15
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_o_coelho_pensante.txt 3 16
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_o_coelho_pensante.txt 3 16
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_o_coelho_pensante.txt 3 16
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_o_coelho_pensante.txt 3 16
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_o_coelho_pensante.txt 3 16
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_Lacos_de_Familia.txt 3 17
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_Lacos_de_Familia.txt 3 17
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_Lacos_de_Familia.txt 3 17
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_Lacos_de_Familia.txt 3 17
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_Lacos_de_Familia.txt 3 17
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Cidade_Sitiada.txt 3 18
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Cidade_Sitiada.txt 3 18
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Cidade_Sitiada.txt 3 18
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Cidade_Sitiada.txt 3 18
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Cidade_Sitiada.txt 3 18
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Paixao_segundo_GH.txt 3 19
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Paixao_segundo_GH.txt 3 19
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Paixao_segundo_GH.txt 3 19
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Paixao_segundo_GH.txt 3 19
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\cl_A_Paixao_segundo_GH.txt 3 19
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_prisioneiro.txt 5 20
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_prisioneiro.txt 5 20
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_prisioneiro.txt 5 20
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_prisioneiro.txt 5 20
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_prisioneiro.txt 5 20
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_AS_AVENTURAS_DE_TIBICUERA.txt 5 21
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_AS_AVENTURAS_DE_TIBICUERA.txt 5 21
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_AS_AVENTURAS_DE_TIBICUERA.txt 5 21
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_AS_AVENTURAS_DE_TIBICUERA.txt 5 21
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_AS_AVENTURAS_DE_TIBICUERA.txt 5 21
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_senhor_embaixador.txt 5 22
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_senhor_embaixador.txt 5 22
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_senhor_embaixador.txt 5 22
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_senhor_embaixador.txt 5 22
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_senhor_embaixador.txt 5 22
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_um_certo_capitao_rodrigo.txt 5 23
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_um_certo_capitao_rodrigo.txt 5 23
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_um_certo_capitao_rodrigo.txt 5 23
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_um_certo_capitao_rodrigo.txt 5 23
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_um_certo_capitao_rodrigo.txt 5 23
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_o_retrato1.txt 5 24
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_o_retrato1.txt 5 24
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_o_retrato1.txt 5 24
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_o_retrato1.txt 5 24
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_o_retrato1.txt 5 24
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_o_retrato2.txt 5 25
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_o_retrato2.txt 5 25
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_o_retrato2.txt 5 25
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_o_retrato2.txt 5 25
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ev_o_retrato2.txt 5 25
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_tieta.txt 4 26
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_tieta.txt 4 26
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_tieta.txt 4 26
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_tieta.txt 4 26
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_tieta.txt 4 26
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_cacau.txt 4 27
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_cacau.txt 4 27
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_cacau.txt 4 27
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_cacau.txt 4 27
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_cacau.txt 4 27
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_jubiaba.txt 4 28
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_jubiaba.txt 4 28
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_jubiaba.txt 4 28
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_jubiaba.txt 4 28
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_jubiaba.txt 4 28
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_suor.txt 4 29
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_suor.txt 4 29
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_suor.txt 4 29
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_suor.txt 4 29
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_suor.txt 4 29
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_menino_grapiuna.txt 4 30
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_menino_grapiuna.txt 4 30
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_menino_grapiuna.txt 4 30
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_menino_grapiuna.txt 4 30
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_menino_grapiuna.txt 4 30
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_FARDA_FARDAO_CAMISOLA_DORMIR.txt 4 31
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_FARDA_FARDAO_CAMISOLA_DORMIR.txt 4 31
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_FARDA_FARDAO_CAMISOLA_DORMIR.txt 4 31
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_FARDA_FARDAO_CAMISOLA_DORMIR.txt 4 31
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_FARDA_FARDAO_CAMISOLA_DORMIR.txt 4 31
python extract_ngram.py 2 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_O_Gato_Malhado_e_a_Andorinha_Sinha.txt 4 11	
python extract_ngram.py 3 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_O_Gato_Malhado_e_a_Andorinha_Sinha.txt 4 11	
python extract_ngram.py 4 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_O_Gato_Malhado_e_a_Andorinha_Sinha.txt 4 11	
python extract_ngram.py 5 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_O_Gato_Malhado_e_a_Andorinha_Sinha.txt 4 11	
python extract_ngram.py 6 C:\Users\edusm\OneDrive\Documentos\uff\trabalhos\inteligencia_artificial\ja_O_Gato_Malhado_e_a_Andorinha_Sinha.txt 4 11	
